# Generated by Django 3.2 on 2022-01-18 02:13

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_user',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('contact_number', models.CharField(db_column='contact_number', max_length=20)),
                ('app_active', models.BooleanField(db_column='app_active')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentIssue',
            fields=[
                ('seq', models.BigAutoField(db_column='Seq', primary_key=True, serialize=False)),
                ('mon_m', models.BooleanField(db_column='mon_m')),
                ('mon_a', models.BooleanField(db_column='mon_a')),
                ('mon_e', models.BooleanField(db_column='mon_e')),
                ('tue_m', models.BooleanField(db_column='tue_m')),
                ('tue_a', models.BooleanField(db_column='tue_a')),
                ('tue_e', models.BooleanField(db_column='tue_e')),
                ('wed_m', models.BooleanField(db_column='wed_m')),
                ('wed_a', models.BooleanField(db_column='wed_a')),
                ('wed_e', models.BooleanField(db_column='wed_e')),
                ('thu_m', models.BooleanField(db_column='thu_m')),
                ('thu_a', models.BooleanField(db_column='thu_a')),
                ('thu_e', models.BooleanField(db_column='thu_e')),
                ('fri_m', models.BooleanField(db_column='fri_m')),
                ('fri_a', models.BooleanField(db_column='fri_a')),
                ('fri_e', models.BooleanField(db_column='fri_e')),
                ('sat_m', models.BooleanField(db_column='sat_m')),
                ('sat_a', models.BooleanField(db_column='sat_a')),
                ('sat_e', models.BooleanField(db_column='sat_e')),
                ('sun_m', models.BooleanField(db_column='sun_m')),
                ('sun_a', models.BooleanField(db_column='sun_a')),
                ('sun_e', models.BooleanField(db_column='sun_e')),
                ('q_career', models.BooleanField(blank=True, db_column='q_Career')),
                ('q_family', models.BooleanField(blank=True, db_column='q_Family')),
                ('q_stress', models.BooleanField(blank=True, db_column='q_Stress')),
                ('q_relationship', models.BooleanField(blank=True, db_column='q_Relationship')),
                ('q_suicide', models.BooleanField(blank=True, db_column='q_Suicide')),
                ('q_violence', models.BooleanField(blank=True, db_column='q_Violence')),
                ('q_homo', models.BooleanField(blank=True, db_column='q_Homo')),
                ('q_trauma', models.BooleanField(blank=True, db_column='q_Trauma')),
                ('q_other', models.CharField(blank=True, db_column='q_Other', max_length=300)),
                ('creatdt', models.DateTimeField(blank=True, db_column='CreatDt')),
                ('updatedt', models.DateTimeField(blank=True, db_column='UpdateDt')),
                ('user_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
