# Generated by Django 3.2 on 2022-01-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_appointmentcalander_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentcalander',
            name='updateuser',
            field=models.IntegerField(blank=True, db_column='UpdateUser', default=1),
            preserve_default=False,
        ),
    ]
