# Generated by Django 3.2 on 2022-01-14 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('seq', models.BigAutoField(db_column='Seq', primary_key=True, serialize=False)),
                ('news_title', models.CharField(blank=True, db_column='NewsTitle', max_length=100)),
                ('news_content', models.CharField(blank=True, db_column='NewsContent', max_length=400)),
                ('news_link', models.CharField(blank=True, db_column='NewsLink', max_length=200)),
                ('news_location', models.CharField(blank=True, db_column='NewsLocation', max_length=50)),
                ('active', models.BooleanField(blank=True, db_column='Active')),
                ('creatdt', models.DateTimeField(blank=True, db_column='CreatDt')),
                ('updatedt', models.DateTimeField(blank=True, db_column='UpdateDt')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
