# Generated by Django 3.2 on 2021-04-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInformation',
            fields=[
                ('Seq', models.BigAutoField(db_column='Seq', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='ID', max_length=10)),
                ('hosp', models.CharField(db_column='Hosp', max_length=10)),
                ('firstname', models.CharField(db_column='FirstName', max_length=20)),
                ('lastname', models.CharField(db_column='LastName', max_length=20)),
                ('birthday', models.DateTimeField(db_column='BirthDay')),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], db_column='Gender', max_length=10, null=True)),
                ('blood', models.CharField(blank=True, db_column='Blood', max_length=3, null=True)),
                ('tel', models.CharField(blank=True, db_column='Tel', max_length=20, null=True)),
                ('creatdt', models.DateTimeField(auto_now_add=True, db_column='CreatDt')),
                ('modifydt', models.DateTimeField(auto_now=True, db_column='ModifyDt')),
            ],
            options={
                'db_table': 'home',
            },
        ),
    ]
